### ISSUE TITLE
Controls don't adopt Dark Theme automatically like those native controls

### ISSUE THREAD

**Issue by SunshineSpring666** [syncfusion/xamarin-demos#22] opened 2020-05-16 13:06 UTC
Syncfusion controls are awesome. Here I encounter a little problem when trying to support dark mode. 

When setting the XAML of Xamarin.Forms projects to Dark Theme, the native controls will be dark, but some Syncfusion control doesn't automatically adopt the Dark Theme. Instead, each control (e.g., AutoComplete, DataGrid, etc.) needed to be configured with specified attirbutes like BackgroundColor, TextColor and so on, in order to provide the user with a proper Dark Theme.

Are there any ways to make all the Syncfusion control go with the theme configuration automatically, just like those native controls? Thanks a lot.

**Comment by RabhiaBehamK** [comment] 2020-05-19 11:53
Hi  SunshineSpring666,

We have prepared the sample to achieve your requirement using Syncfusion Themes. Please find the below help documentation and code snippet  for your reference,

**Link: https://help.syncfusion.com/xamarin/themes/themes**

**Code Snippet:**
`<ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                
                <syncTheme:DarkTheme />
            </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>`

**Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/ThemeApplication1814553054**

**Screenshot:**

<img width="150" alt="Image" src="https://user-images.githubusercontent.com/39405635/82323069-23824a80-99f5-11ea-9ad1-d466aef54718.png">

Please check with the sample and let us know if you have any concerns.

**Comment by SunshineSpring666** [comment] 2020-05-20 14:20
Thanks, Rabhia. 
    Actually I added the "Automatic merging" resource dictionary in the Application.Resource tag, as instructed in the documentation. But controls like SfNumericUpDown and DataGrid don't seem to adopt the dark theme automatically. 
    I also tried the "Manual merging" instruction, but it didn't work as expected. 
    I guess I might have misconfigured something. Currently I adopt the workaround of setting foreground/background/text color attributes of each type of syncfusion control explicitly.
    No further help needed on this. But in case your teams are interested in why it happens, here is the environment information I test with: Visual Studio 2019 16.7.0 Preview 1 +  Xamarin.Forms 4.7.0.813-pre2  +  Syncfusion.Xamarin 18.1.0.53.
    Thank you again for all these detailed instructions and help.

**Closed** 2020-05-26 16:03 UTC

**Comment by RabhiaBehamK** [comment] 2020-05-28 05:16
HI @SunshineSpring666 ,

Thanks for the update.

We have also checked with the SfNumericUpDown and SfDataGrid theme and it is working fine at our end. Please use the below samples with which we have ensured.

**Sample Links:** 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/DataGridTheme-1331806756  
https://www.syncfusion.com/downloads/support/directtrac/general/ze/ThemeApplication2125730359  
 
**Screenshot:** 
<img width="207" alt="thumbnail_image001" src="https://user-images.githubusercontent.com/39405635/83101658-754f6280-a0d0-11ea-8f68-740270cb4c5a.png">

Please check with the above and if the issue still occurs please modify the sample with the issue reproducing steps which will be helpful for us to analyze and provide the solution at the earliest.

**Comment by SunshineSpring666** [comment] 2020-05-31 14:55
Thanks, Rabhia. As you mentioned, the way of theming control works ok for some controls on some platforms. Maybe I still do something wrong, it doesn't seem to automatically make all controls show properly on all platforms in Dark Theme. For example, the NumericUpDown on UWP, the autocomplete on Android, etc. However, some simple workaround (by setting corresponding color property on global scale) makes it work perfectly.
Thanks all for your kindly reply. Have a good day.

**Comment by RabhiaBehamK** [comment] 2020-06-04 12:49
Hi @SunshineSpring666,

Thanks for your update.

We are glad that the issue is resolved at your end.

Please get back to us if you need further assistance.
